config/routes.rb
Rails.application.routes.draw do

  resources :websites

  get 'home' => "welcome#home"

  devise_for :users
  root to: "welcome#home"

  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
    match 'post_action', via: [ :post, :options]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: :true
  belongs_to :website

  def name_in_caps
    name.upcase
  end

  # @site.events.where(name: "home").data_for_chart
  def self.data_for_chart
    data = {}
    groups = all.group_by {|event| event.created_at.to_date }
    groups.each {|date, events| data[date] = events.count }
    data
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :websites, dependent: :destroy
end

app/models/website.rb
require 'uri'

class Website < ActiveRecord::Base

  validates :url, presence: true, uniqueness:true, format: { with: URI::regexp(%w(http https)) }

  belongs_to :user
  has_many :events, dependent: :destroy

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def create
    @website = Website.find_by(url: request.env['HTTP_ORIGIN'])
    if @website.nil?
      render json: "Unregistered Application", status: :unprocessable_entity
    else
      @event = @website.events.build(event_params)
        if @event.save
          render json: @event, status: :created
        else
          render @event.errors, status: :unprocessable_entity
        end
    end
  end

private
  def event_params
    params.permit(:name)
  end

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end
 
  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'
 
      render :text => '', :content_type => 'text/plain'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :authenticate_user!

  def index
    @websites = current_user.websites.all
  end

  def show
    @website = Website.find(params[:id])
    @events = @website.events.group_by(&:name)
  end

  def new
    @website = Website.new
  end

  def create
    @website = current_user.websites.build(params.require(:website).permit(:url))
    if @website.save
      flash[:notice] = "Website Registered!"
      redirect_to websites_path
    else
      flash[:error] = "There was an error saving your website."
      render :new
    end
  end

  def destroy
    @website = Website.find(params[:id])

    if @website.destroy
      flash[:notice] = "No longer tracking #{@website.url}."
      redirect_to websites_path
    else
      flash[:error] = "There was an error deleting the website."
      render websites_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    if current_user
     redirect_to websites_path
    else
      render :home
    end        
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clickametrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_user_session_path %> or
    <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  
  

    <%= yield %>


</body>
</html>

app/views/websites/index.html.erb
<h1>Your Websites</h1>

<h3><%= link_to "Track a new website", new_website_path %></h3>
<% @websites.each do |website| %>
  <p><%= link_to website.url, website_path(website.id) %> <small><%= link_to "Delete", website_path(website.id), method: :delete %></small>
<% end %>

app/views/websites/new.html.erb
<%= form_for @website do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Save" %>
<% end %>

app/views/websites/show.html.erb
<h1>Events for <%= "#{@website.url}" %></h1>
<%= pie_chart @website.events.group(:name).count %>
<% @events.each do |name, eventlist| %>
  <%= "Your website had had #{eventlist.count} #{name}" %>
<% end %>
<%= line_chart @website.events.data_for_chart %>

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>